<?php

declare(strict_types=1);

namespace LeNewBlack\Wholesale\Model\Order;

use LeNewBlack\Wholesale\Model\Retailer\Address;

final class Order
{
    /**
     * @param OrderItem[] $items
     */
    public function __construct(
        public readonly ?string $reference = null,
        public readonly ?string $create_time = null,
        public readonly ?string $update_time = null,
        public readonly ?string $confirmation_time = null,
        public readonly ?string $cancellation_time = null,
        public readonly ?string $auto_cancel_on = null,
        public readonly ?string $delivery_start_on = null,
        public readonly ?string $delivery_end_on = null,
        public readonly ?string $delivery_incoterm_ref = null,
        public readonly ?string $price_list_code = null,
        public readonly ?string $sales_catalog_code = null,
        public readonly ?string $purchase_order_reference = null,
        public readonly ?string $retailer_reference = null,
        public readonly ?string $retailer_name = null,
        public readonly ?string $buyer_name = null,
        public readonly ?string $buyer_first_name = null,
        public readonly ?string $buyer_email = null,
        public readonly ?string $sales_person_name = null,
        public readonly ?string $sales_person_first_name = null,
        public readonly ?string $sales_person_email = null,
        public readonly ?int $selection_id = null,
        public readonly ?float $amount_order = null,
        public readonly ?float $amount_shipping = null,
        public readonly ?float $amount_promotion = null,
        public readonly ?float $amount_discount = null,
        public readonly ?float $amount_tax = null,
        public readonly ?float $amount_total = null,
        public readonly ?float $amount_total_tax_inclusive = null,
        public readonly ?float $price_total = null,
        public readonly ?float $price_total_prediscount = null,
        public readonly ?string $currency = null,
        public readonly ?float $discount_rate = null,
        public readonly bool $inventory_tracking = false,
        public readonly ?string $inventory_type = null,
        public readonly ?string $order_mode = null,
        public readonly ?string $order_type = null,
        public readonly ?string $order_picking = null,
        public readonly ?string $status = null,
        public readonly ?string $comment = null,
        public readonly ?string $terms_of_delivery = null,
        public readonly ?string $terms_of_payment = null,
        public readonly ?string $retailer_extra_1 = null,
        public readonly ?string $retailer_extra_2 = null,
        public readonly ?string $retailer_extra_3 = null,
        public readonly ?string $retailer_extra_4 = null,
        public readonly ?string $retailer_extra_5 = null,
        public readonly ?Address $billing_address = null,
        public readonly ?Address $delivery_address = null,
        public readonly array $items = [],
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            reference: $data['reference'] ?? null,
            create_time: $data['create_time'] ?? null,
            update_time: $data['update_time'] ?? null,
            confirmation_time: $data['confirmation_time'] ?? null,
            cancellation_time: $data['cancellation_time'] ?? null,
            auto_cancel_on: $data['auto_cancel_on'] ?? null,
            delivery_start_on: $data['delivery_start_on'] ?? null,
            delivery_end_on: $data['delivery_end_on'] ?? null,
            delivery_incoterm_ref: $data['delivery_incoterm_ref'] ?? null,
            price_list_code: $data['price_list_code'] ?? null,
            sales_catalog_code: $data['sales_catalog_code'] ?? null,
            purchase_order_reference: $data['purchase_order_reference'] ?? null,
            retailer_reference: $data['retailer_reference'] ?? null,
            retailer_name: $data['retailer_name'] ?? null,
            buyer_name: $data['buyer_name'] ?? null,
            buyer_first_name: $data['buyer_first_name'] ?? null,
            buyer_email: $data['buyer_email'] ?? null,
            sales_person_name: $data['sales_person_name'] ?? null,
            sales_person_first_name: $data['sales_person_first_name'] ?? null,
            sales_person_email: $data['sales_person_email'] ?? null,
            selection_id: $data['selection_id'] ?? null,
            amount_order: isset($data['amount_order']) ? (float) $data['amount_order'] : null,
            amount_shipping: isset($data['amount_shipping']) ? (float) $data['amount_shipping'] : null,
            amount_promotion: isset($data['amount_promotion']) ? (float) $data['amount_promotion'] : null,
            amount_discount: isset($data['amount_discount']) ? (float) $data['amount_discount'] : null,
            amount_tax: isset($data['amount_tax']) ? (float) $data['amount_tax'] : null,
            amount_total: isset($data['amount_total']) ? (float) $data['amount_total'] : null,
            amount_total_tax_inclusive: isset($data['amount_total_tax_inclusive']) ? (float) $data['amount_total_tax_inclusive'] : null,
            price_total: isset($data['price_total']) ? (float) $data['price_total'] : null,
            price_total_prediscount: isset($data['price_total_prediscount']) ? (float) $data['price_total_prediscount'] : null,
            currency: $data['currency'] ?? null,
            discount_rate: isset($data['discount_rate']) ? (float) $data['discount_rate'] : null,
            inventory_tracking: $data['inventory_tracking'] ?? false,
            inventory_type: $data['inventory_type'] ?? null,
            order_mode: $data['order_mode'] ?? null,
            order_type: $data['order_type'] ?? null,
            order_picking: $data['order_picking'] ?? null,
            status: $data['status'] ?? null,
            comment: $data['comment'] ?? null,
            terms_of_delivery: $data['terms_of_delivery'] ?? null,
            terms_of_payment: $data['terms_of_payment'] ?? null,
            retailer_extra_1: $data['retailer_extra_1'] ?? null,
            retailer_extra_2: $data['retailer_extra_2'] ?? null,
            retailer_extra_3: $data['retailer_extra_3'] ?? null,
            retailer_extra_4: $data['retailer_extra_4'] ?? null,
            retailer_extra_5: $data['retailer_extra_5'] ?? null,
            billing_address: isset($data['billing_address']) ? Address::fromArray($data['billing_address']) : null,
            delivery_address: isset($data['delivery_address']) ? Address::fromArray($data['delivery_address']) : null,
            items: array_map(OrderItem::fromArray(...), $data['items'] ?? []),
        );
    }
}
